import { Metadata } from 'next';
import YamlValidatorPage from '../../yaml-validator-page';

const canonical = 'https://www.yamlvalidator.pro/validator/docker-compose/';
function stringifyJsonLd(data: unknown) {
  return JSON.stringify(data)
    .replace(/</g, '\\u003c')
    .replace(/>/g, '\\u003e')
    .replace(/&/g, '\\u0026')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029');
}

const faqs = [
  {
    q: 'Does this check Docker Compose schema rules?',
    a: 'This page focuses on YAML syntax and parsed structure. Run docker compose config for Compose-specific schema and interpolation checks.',
  },
  {
    q: 'Should I quote port mappings?',
    a: 'Quoting port and volume mappings is often safer, especially when files are generated by templates or processed by multiple parsers.',
  },
  {
    q: 'Is my Compose file stored?',
    a: 'No. The tool runs in your browser and does not upload Compose content to a server.',
  },
];

export const metadata: Metadata = {
  title: 'Docker Compose YAML Validator — Online Compose File Checker',
  description: 'Validate docker-compose.yml files online before docker compose up. Check services, volumes, networks, environment variables, ports, and healthchecks with live line and column feedback.',
  keywords: ['Docker Compose validator', 'docker-compose.yml checker', 'Docker Compose YAML validator', 'Docker config validator', 'Compose file syntax check', 'docker compose config helper', 'Compose services validator', 'YAML port mapping checker'],
  openGraph: {
    title: 'Docker Compose YAML Validator — YAML Config Validator Pro',
    description: 'Validate Docker Compose YAML files with live syntax checking, Tree View inspection, and precise error line numbers.',
    type: 'website',
    url: canonical,
    images: ['/og-image.png'],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Docker Compose YAML Validator',
    description: 'Validate Docker Compose YAML files with live syntax checking, Tree View inspection, and precise error line numbers.',
    images: ['/og-image.png'],
  },
  alternates: {
    canonical,
  },
};

export default function Page() {
  const schema = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'WebPage',
        name: 'Docker Compose YAML Validator',
        url: canonical,
        description: metadata.description,
        isPartOf: { '@type': 'WebSite', name: 'YAML Config Validator Pro', url: 'https://www.yamlvalidator.pro/' },
      },
      {
        '@type': 'SoftwareApplication',
        name: 'Docker Compose YAML Validator',
        url: canonical,
        applicationCategory: 'DeveloperApplication',
        operatingSystem: 'Any',
        isAccessibleForFree: true,
        offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
        featureList: [
          'Live YAML syntax validation',
          'Public URL loading with ?url=',
          'Open local YAML files',
          'Copy shareable YAML links',
          'Tree View parsed structure inspection',
        ],
      },
      {
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://www.yamlvalidator.pro/' },
          { '@type': 'ListItem', position: 2, name: 'Docker Compose YAML Validator', item: canonical },
        ],
      },
      {
        '@type': 'FAQPage',
        mainEntity: faqs.map((faq) => ({
          '@type': 'Question',
          name: faq.q,
          acceptedAnswer: { '@type': 'Answer', text: faq.a },
        })),
      },
    ],
  };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: stringifyJsonLd(schema) }} />
      <YamlValidatorPage defaultScenario="docker-compose" />
    </>
  );
}
